<br/>

<form action="../index.php" method="post">

<div class="row">
  	<div class="panel panel-primary">
		<div class="panel-heading">Airport List</div>
		<div class="panel-body">
			<select name="country">
				<option>--chọn--</option>
			<?php foreach($countries as $c){ ?>
				<option <?php echo $country==$c['country']?"selected":""; ?> value="<?= $c['country']; ?>" ><?= $c['country']; ?></option>
			<?php }?>
			</select>
			<input type="submit" name="btnShow"> 
			<hr/>
			<?php if (!empty($country)){ ?>
	        <table class="table table-striped table-bordered table-hover table-condensed">
		         <thead>
		            <tr>
		              <th>No.</th>
		              <th>Code</th>
		              <th>Name</th>
		              <th>City</th>
		              <th>State</th>
		              <th>Country</th>
		              <th>Action</th>		             
		            </tr>
		        </thead>
	          	<tbody>
	          	<?php $i = 0; foreach($allAirport as $m) { ?>
		            <tr>
		              <td><?php echo ++$i; ?></td>
		              <td><?= $m->code; ?></td>
		              <td><?= $m->name; ?></td>
		              <td><?= $m->city; ?></td>
		              <td><?= $m->state; ?></td>
		              <td><?= $m->country; ?></td>
		              <td class="text-center"><a  data-toggle="confirmation" data-title="Bạn có chắc muốn xóa <?php echo $m->name ?>?" href="/airport_delete.php?code=<?= $m->code; ?>"><i class="fa fa-trash"></i></a></td>
		          </td>
		            </tr>
	          	<?php } ?>
	     		</tbody>
	  		</table>
	  		<?php } ?>
		</div>
	</div>
</div>

</form>